[package]
name = "udp_tester"
version = "0.1.0"
authors = ["Thomas <thomastimmer11@hotmail.com>"]
edition = "2018"
description = "UPD server that handles statsd metrics"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "*", features = ["rt-multi-thread", "net", "io-util", "fs", "macros", "signal"]}
tokio-util = {version = "*", features = ["codec", "net"]}
tokio-stream = "*"
# statsd-parser = "0.3.0"
statsd-parser = {git="https://github.com/thomas9911/statsd_parser", branch="main"}


structopt = { version = "0.3", default-features = false }